Milestone 3: Add and remove
medaminedev66/to-do-list pull request #3
Opened 2021-08-19 15:34 UTC by medaminedev66

- Add `task.js` file, create Task class.
- Add `addTask` and `removeTask` functions to `tasks.js` file.
- Add remove icon to `listContainer`.
- Add event listener to add icon and `input-text` class .
- Add event Listener to remove icon.
- Update all remaining items' indexes after deleting a task.

2021-08-19 16:45 UTC, henatan99 requested changes
Hi @medaminedev66 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-19 16:45 UTC, henatan99 commented on src/tasks.js
> +
- [ ] In the project's specific requirements, a function for editing task descriptions is required to be implemented. You can add it here or any other file that suits you. Kindly add the edit description method. :pray: You can revisit the project's requirements [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md).
- [ ] In the project's specific requirements, the function for the "Clear all completed" button (use filter() method) is required to be implemented. Again you can revisit the project's requirements [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md).

2021-08-19 16:45 UTC, henatan99 commented on src/tasks.js
> +
- [ ] In the project's specific requirements, a function for editing task descriptions is required to be implemented. You can add it here or any other file that suits you. Kindly add the edit description method. :pray: You can revisit the project requirements [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md).

2021-08-19 16:45 UTC, henatan99 commented on dist/index.html
> -        <div class="the-list"></div>
- [ ] I think you should have a "Clear all completed" button below this element. In this milestone, you are also required to be able to delete all the completed tasks in one button click. :+1: Please look back to the project's requirements [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md).

2021-08-21 06:12 UTC, hemant-soni-vst-au4 requested changes
Hi @medaminedev66, 

Good job so far. 👍 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- 

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 06:12 UTC, hemant-soni-vst-au4 commented on dist/index.html
> +<script defer src="/to-do-list/main.js"></script></head>
- [ ] On the first instance I tried to run the project locally but functions were not working then I noticed this. It is working perfectly as `<script defer src="main.js"></script>`. Kindly try to update to the correct path.

2021-08-21 06:12 UTC, hemant-soni-vst-au4 commented on README.md
>  - In terminal or Command line. Navigate to a directory in your local storage where you'd like to store the project and paste ```https://github.com/medaminedev66/to-do-list.git```
- [ Optional] Kindly try to update the `Live link` and correct the information for getting started in your README file. Like `npm install`, `npm run build` and `npm start` are some of the information missing to start a project locally.

2021-08-21 09:35 UTC, hemant-soni-vst-au4 approved these changes
Hi @medaminedev66, 

Good work on making the requested changes. 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 09:56 UTC, medaminedev66 commented
Thanks to you, @hemant-soni-vst-au4 , for your time to review my project.

2021-08-21 09:58 UTC, medaminedev66 commented
Thanks to you, @hemant-soni-vst-au4 , for your time to review my project.

2021-08-21 09:59 UTC, medaminedev66 commented
Thanks to you, @hemant-soni-vst-au4 , for your time to review my project.

2021-08-21 09:59 UTC, merged